export const MONTH_DATA = [
  {
    month: 0,
    name: "January",
    image: "/images/january.png",
    accent: "#4A90D9",
    gradient: "from-blue-900 via-slate-800 to-blue-700",
    mood: "Arctic",
    description: "Crisp mountain peaks kissed by winter's first light",
    timeOfDay: "dawn",
  },
  {
    month: 1,
    name: "February",
    image: "/images/february.png",
    accent: "#C084FC",
    gradient: "from-purple-900 via-pink-800 to-rose-600",
    mood: "Romantic",
    description: "Lavender fields bloom under a dreamy twilight sky",
    timeOfDay: "dusk",
  },
  {
    month: 2,
    name: "March",
    image: "/images/march.png",
    accent: "#F472B6",
    gradient: "from-pink-900 via-rose-700 to-pink-400",
    mood: "Bloom",
    description: "Cherry blossoms drift like pink snow in morning breeze",
    timeOfDay: "morning",
  },
  {
    month: 3,
    name: "April",
    image: "/images/april.png",
    accent: "#4ADE80",
    gradient: "from-green-900 via-emerald-700 to-yellow-500",
    mood: "Renewal",
    description: "Golden light pierces the clouds after spring rain",
    timeOfDay: "afternoon",
  },
  {
    month: 4,
    name: "May",
    image: "/images/may.png",
    accent: "#34D399",
    gradient: "from-emerald-900 via-green-700 to-lime-500",
    mood: "Lush",
    description: "Ancient forests glow as sunbeams find their way through",
    timeOfDay: "morning",
  },
  {
    month: 5,
    name: "June",
    image: "/images/june.png",
    accent: "#FB923C",
    gradient: "from-orange-900 via-amber-700 to-yellow-400",
    mood: "Radiant",
    description: "Turquoise waves meet golden sand in paradise",
    timeOfDay: "golden",
  },
  {
    month: 6,
    name: "July",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1400&q=85&fit=crop",
    accent: "#EF4444",
    gradient: "from-red-900 via-orange-800 to-amber-600",
    mood: "Fire",
    description: "Mountains ablaze beneath an explosion of color",
    timeOfDay: "sunset",
  },
  {
    month: 7,
    name: "August",
    image: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1400&q=85&fit=crop",
    accent: "#818CF8",
    gradient: "from-indigo-900 via-blue-900 to-violet-800",
    mood: "Cosmic",
    description: "The Milky Way paints its reflection on still waters",
    timeOfDay: "night",
  },
  {
    month: 8,
    name: "September",
    image: "https://images.unsplash.com/photo-1477414348463-c0eb7f1359b6?w=1400&q=85&fit=crop",
    accent: "#F97316",
    gradient: "from-orange-900 via-amber-800 to-yellow-600",
    mood: "Harvest",
    description: "Autumn's cathedral of gold and crimson",
    timeOfDay: "afternoon",
  },
  {
    month: 9,
    name: "October",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1400&q=85&fit=crop",
    accent: "#06B6D4",
    gradient: "from-teal-900 via-cyan-800 to-slate-700",
    mood: "Mystical",
    description: "Enigmatic mists cloak the ancient pines",
    timeOfDay: "dawn",
  },
  {
    month: 10,
    name: "November",
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1400&q=85&fit=crop",
    accent: "#FDA4AF",
    gradient: "from-rose-900 via-orange-800 to-pink-500",
    mood: "Reverie",
    description: "Silhouettes emerge from a blush-tinted morning fog",
    timeOfDay: "morning",
  },
  {
    month: 11,
    name: "December",
    image: "https://images.unsplash.com/photo-1551582045-6ec9c11d8697?w=1400&q=85&fit=crop",
    accent: "#60A5FA",
    gradient: "from-slate-900 via-blue-900 to-indigo-800",
    mood: "Cozy",
    description: "Warmth glows from within as winter embraces everything",
    timeOfDay: "night",
  },
];

export const MOOD_OPTIONS = [
  { emoji: "😊", label: "Happy", color: "#FCD34D", bg: "rgba(252,211,77,0.2)" },
  { emoji: "💻", label: "Work", color: "#60A5FA", bg: "rgba(96,165,250,0.2)" },
  { emoji: "🎉", label: "Fun", color: "#F472B6", bg: "rgba(244,114,182,0.2)" },
  { emoji: "😴", label: "Rest", color: "#A78BFA", bg: "rgba(167,139,250,0.2)" },
  { emoji: "🧘", label: "Calm", color: "#34D399", bg: "rgba(52,211,153,0.2)" },
  { emoji: "⚡", label: "Energy", color: "#FBBF24", bg: "rgba(251,191,36,0.2)" },
  { emoji: "❤️", label: "Love", color: "#F87171", bg: "rgba(248,113,113,0.2)" },
  { emoji: "🌧️", label: "Low", color: "#94A3B8", bg: "rgba(148,163,184,0.2)" },
];

export const INTENT_MODES = [
  { id: "planning", label: "📅 Planning", description: "Structured layout for events" },
  { id: "productivity", label: "🎯 Productivity", description: "Sharp focus mode" },
  { id: "personal", label: "🧘 Personal", description: "Soft & reflective" },
] as const;

export const RANGE_SUGGESTIONS = [
  { label: "Weekend Getaway", days: 2, icon: "🌅", startDay: 5 },
  { label: "Long Weekend", days: 3, icon: "🏖️", startDay: 4 },
  { label: "Work Sprint", days: 5, icon: "⚡", startDay: 0 },
  { label: "Full Week", days: 7, icon: "📅", startDay: 0 },
  { label: "Focus Block", days: 4, icon: "🎯", startDay: 0 },
  { label: "Adventure Trip", days: 10, icon: "🏔️", startDay: 0 },
];

export const PACKING_LIST_ITEMS = [
  "📋 Travel documents",
  "💊 Medications",
  "👔 Clothes & accessories",
  "🔌 Chargers & adapters",
  "📷 Camera & gear",
  "💳 Cards & cash",
  "🧴 Toiletries",
  "📚 Books / Entertainment",
  "🎧 Headphones",
  "🌂 Weather essentials",
];

export const MOCK_WEATHER = [
  { icon: "☀️", temp: "24°C", desc: "Sunny" },
  { icon: "⛅", temp: "18°C", desc: "Partly cloudy" },
  { icon: "🌧️", temp: "14°C", desc: "Light rain" },
  { icon: "🌤️", temp: "22°C", desc: "Clear" },
  { icon: "⛈️", temp: "16°C", desc: "Thunderstorm" },
  { icon: "🌬️", temp: "12°C", desc: "Windy" },
  { icon: "🌈", temp: "20°C", desc: "After rain" },
];
